// RootLayoutServer.tsx
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mangoliya Grand",
  description: "Generated by create next app",
};

const font = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: "--font-dm-sans",
});

export default function RootLayoutServer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Google Tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-WHXP5YHDZF"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-WHXP5YHDZF');
            `,
          }}
        />
      </head>
      <body
        className={font.className}
      >

        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KGJ2S772"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>

        {children}
      </body>
    </html>
  );
}
